version: "3.9"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Load environment variables
    ports:
      - "3005:3005"
      - "5050:5050"  # WebSocket port exposed
    networks:
      - app-network
    command: ["/bin/sh", "-c", "npx prisma migrate deploy --schema=./src/prisma/schema.prisma && npm run start"]

networks:
  app-network:
    driver: bridge
