version: "3.9"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL= # Ensure this matches the db service
    ports:
      - "3005:3005"
      - "5050:5050"  # WebSocket port exposed
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=postgres  # Corrected username
      - POSTGRES_PASSWORD=postgres_password  # Ensure this matches `DB_PASSWORD`
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
