version: "3.9"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Load environment variables from .env
    ports:
      - "3005:3005"
      - "5050:5050"  # WebSocket port exposed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
